baseURL = "https://orderly.bot"
languageCode = "en-gb"
title = "Orderly"
themesDir = "../themes"
theme = "hugo-bearblog"
enableRobotsTXT = true

[permalinks]
  blog = "/:slug/"
  tags = "/tags/:slug"

[params]
  description = "AI-powered daily digest of UK parliamentary debates. Stay informed with concise, accessible summaries of what's happening inside the belly of the beast."
  title = "Orderly"
  enablePostNavigator = true

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true